### ISSUE TITLE
How to ingest local data into kowalski

### ISSUE THREAD

**Issue by rstrausb** [skyportal/kowalski#187] opened 2023-02-22 18:02 UTC
Looking for a tutorial on what to do after adding a new stream to kowalski.  I am adding a new instrument to kowalski called TURBO. I have followed the steps in the tutorial about adding WINTER to kowalski.  I think I have things set up correctly as I can successfully complete the test step using TURBO data.  I now don't know what to do to have kowalski ingest local turbo data and then post candidates to skyportal.

**Comment by mcoughlin** [comment] 2023-02-22 18:12
@rstrausb Do you have a branch to open a PR? It will be hard to look at where things stand without it.

**Comment by rstrausb** [comment] 2023-02-22 18:21
I do not.  Shall I make one?

**Comment by mcoughlin** [comment] 2023-02-22 18:21
Yes.

**Comment by rstrausb** [comment] 2023-02-22 19:30
Here's the branch
https://github.com/rstrausb/kowalski
not sure if there is a better way to link it.

**Comment by mcoughlin** [comment] 2023-02-22 19:31
@rstrausb Generally folks make branches but this OK for the moment. Can you open a PR?

**Comment by rstrausb** [comment] 2023-02-22 19:38
I think I set up the PR correctly.  Let me know if not.

**Comment by mcoughlin** [comment] 2023-02-22 19:41
@rstrausb Why are there 97 files?

**Comment by rstrausb** [comment] 2023-02-22 19:45
It is counting every file as a new file maybe? I probably didn't set things up correctly.

**Comment by mcoughlin** [comment] 2023-02-22 19:46
@rstrausb Yeah this is impossible to understand as is.

**Comment by rstrausb** [comment] 2023-02-22 19:47
@mcoughlin So I should instead make a branch and then open the PR on the branch?

**Comment by Theodlz** [comment] 2023-02-22 19:49
I think you've put the actual kowalski code in a Kowalski folder. Your current PR is as if you had uploaded the top folder in which you had Kowalski, not Kowalski itself with added files.

**Comment by rstrausb** [comment] 2023-02-22 19:54
I can just delete the branch I created in my directory and start over.  What are the steps I should do next time to avoid that happening again?

**Comment by Theodlz** [comment] 2023-02-22 19:57
Ok so I had a better look at it. The problem isn't what I thought, the files are folders look normal
The problem here is that you submitted what looks like a bunch of config files and other files you probably submitted by mistake

**Comment by Theodlz** [comment] 2023-02-22 19:58
Also, I believe there is a type of file to have multiple alerts in one file, rather than one file per alert. That's something you might want to look into to avoid having to commit so many individual files.

**Comment by Theodlz** [comment] 2023-02-22 20:01
Ah and I was that your PR comes from your master branch. I suggest you never commit any code to your master branch but on a dedicated branch. That way, you can merge new changes from upstream into your master branch, and then merge them in the branch where you are working. By committing to your master branch you're "breaking" your fork in a way, as you have now a Kowalski that differs from the original one. SO let's say you want to open a 2nd PR later, you won't be able to clone Kowalski:master easily.

**Comment by rstrausb** [comment] 2023-02-22 20:06
@Theodlz I'm not a regular github user.  If you think I should set things up differently, let me know.  The "master" I did the PR from is just a place I dumped files, its not where I have been actively working on things.

**Comment by mcoughlin** [comment] 2023-02-22 20:07
@rstrausb the skyportal contribution guide is pretty good: https://skyportal.io/docs/contributing.html

**Comment by rstrausb** [comment] 2023-02-22 23:20
@mcoughlin @Theodlz I redid the forking and branching using the instruction from the link michael sent.  Here is the link to the new pull request https://github.com/skyportal/kowalski/pull/189.  Let me know if this one worked better than the last one.  I tried to include only the necessary files this time.  I verified that things still work the same on this branch and they do.  I can run ./kowalski.py test and see the same behavior as before, with the test broker and test ingester for TURBO both passing.

**Comment by Theodlz** [comment] 2023-03-07 18:04
Hi @rstrausb, the latest PR on main added additional information about how to ingest local alerts in Kowalski, and more generally should help with getting Kowalski to run locally. Please have a look (or even try running the code), and let's close this issue if you think that it's clear enough now.

**Closed** 2024-07-11 01:04 UTC
Labels: enhancement
